language: python

CIBW_TEST_REQUIRES: pytest
CIBW_BEFORE_BUILD: pip install -r requirements.txt
CIBW_TEST_COMMAND: pytest {project}/tests

jobs:
  include:
    # perform a linux build
    - os: linux
      language: shell
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=joerick
      # Note: TWINE_PASSWORD is set in Travis settings
    - CC="gcc"  

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi