# In this configuration, the package is tested against multiple versions of python
# on Linux and on one version of Python on Windows. If and only if all tests pass
# will the wheels be built and deployed. Further, deployment is only initiated if
# the current branch is "master", the current commit is tagged, and the current
# repo is yours (e.g. it won't run on a Pull Request). For convenience, a source
# distribution is also created.

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" = windows ]]; then
        choco install python --version 3.8.0
        export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" = osx ]]; then
        export PATH="/usr/local/bin:$PATH"
        if [ ! -f "/usr/local/bin/gcc-9" ]; then
          brew install gcc@9
        fi

        brew install libomp
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        export CC="/usr/local/bin/gcc"
    fi

install:
  - python -m pip install pytest

script:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install -r python2-requirements.txt; else pip install -r requirements.txt; fi
  - pip install -e .
  - pytest tests/

stages:
  - test
  - codecov
  # Only execute deployment stage on master branch, tagged commits,
  # and from your repository (e.g. not PRs). Replace with your repo name.
  - name: deploy
    if: tag IS present

jobs:
  include:
    # Optional: run a test on Windows
    - os: windows
      language: shell
      name: Test on Windows

    # Code coverage
    - stage: codecov
      name: Add code coverage stats
      services: docker
      install:
        - pip install codecov
        - pip install pytest-cov
        - pip install -e .
      script:
        - pytest --cov=matrixprofile tests/
        - codecov

    # # Deploy on linux
    - stage: deploy
      name: Build and deploy Linux wheels
      services: docker
      install: python -m pip install twine cibuildwheel==1.0.0
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success:
        - python -m twine upload wheelhouse/*.whl --verbose
    # Deploy on mac
    - stage: deploy
      name: Build and deploy macOS wheels
      os: osx
      language: shell
      install: python -m pip install twine cibuildwheel==1.0.0
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success:
        - python -m twine upload wheelhouse/*.whl --verbose
    # Deploy on windows
    - stage: deploy
      name: Build and deploy Windows wheels
      os: windows
      language: shell
      install: python -m pip install twine cibuildwheel==1.0.0
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success:
        - python -m twine upload wheelhouse/*.whl --verbose

env:
  global:
    - TWINE_USERNAME=matrixprofilefoundation
    - MPLBACKEND=agg
      # Note: TWINE_PASSWORD is set in Travis settings